# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerMonitorCli < Formula
  desc ""
  homepage "https://github.com/MichaelTolchinsky/homebrew-docker-monitor-cli"
  version "0.45"

  on_macos do
    url "https://github.com/MichaelTolchinsky/homebrew-docker-monitor-cli/releases/download/v0.45/homebrew-docker-monitor-cli_0.45_darwin_all.tar.gz"
    sha256 "9d99048ead8b0dda0f5170c62294e5b485a7a82decf9e56be9b4939069c3aa19"

    def install
      bin.install "homebrew-docker-monitor-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MichaelTolchinsky/homebrew-docker-monitor-cli/releases/download/v0.45/homebrew-docker-monitor-cli_0.45_linux_arm64.tar.gz"
      sha256 "c7f76f0da204ea203bd785b3ab38a14d5cbd77c71d8e7ae1e0a3b5d66edc9284"

      def install
        bin.install "docker-monitor-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/MichaelTolchinsky/homebrew-docker-monitor-cli/releases/download/v0.45/homebrew-docker-monitor-cli_0.45_linux_amd64.tar.gz"
      sha256 "073acf724533de3c6fa5288e9d4efda819db139952ff522397a8100fb2ed0583"

      def install
        bin.install "docker-monitor-cli"
      end
    end
  end
end
